### ISSUE TITLE
Ripple Example

### ISSUE THREAD

**Issue by pemrouz** [voronianski/flux-comparison#10]
Would be nice have a comparison example for Ripple too, can send a PR if you want. 

Ripple is an extension to the Flux paradigm (closer to the new Relay in scope):

> **Ripple vs Flux**
> 
> Ripple shares key architectural concepts with Flux, such as the single dispatcher, data-flow programming (unidirectional), and views updating when the associated data changes, etc. However, Ripple is an extension to the Flux paradigm, in that the dispatcher will not update only the data/views on the current page, but on all other clients too. Ripple introduces much less proprietary concepts (everything is a resource) and the API aims to embrace standards rather than invent new ones.

https://github.com/pemrouz/ripple

See also the React quick example to get started: https://github.com/pemrouz/ripple-examples

**Comment by voronianski** [comment]
@pemrouz hey, thanks for suggest! I'll be glad to see PR with such example in this repo as well.

**Comment by pemrouz** [comment]
@voronianski: See https://github.com/voronianski/flux-comparison/pull/22. I kept this as a server-less implementation like the rest, but obviously the power with Ripple is having changes ripple across the network to all connected servers/clients.

React doesn't play well with Web Components, so I left it out. But you could easily require the common JSX files, add a wrapper div, then render into that, [like this](https://github.com/pemrouz/ripple-examples/blob/master/minimal-react/index.js#L18).

**Comment by voronianski** [comment]
@pemrouz in order to keep better structure of the repo non-flux examples are no longer accepted.

**Comment by pemrouz** [comment]
What's a "flux example" exactly?
