### ISSUE TITLE
Idea: create a separate folder comparing the isomorphic flux implementations

### ISSUE THREAD

**Issue by goatslacker** [voronianski/flux-comparison#2]
Fluxible, reflux, and alt are doing isomorphic that I know of, and others are adding it too. There should be a separate folder or perhaps this is outside of the scope of this repo and there should be a different project that deals with these comparisons. We can use the same app.

**Comment by voronianski** [comment]
@goatslacker yep, that's an awesome idea! Probably it will be better to separate it as separate github repo/project.

**Comment by voronianski** [comment]
@goatslacker could you start with alt's isomorphic example? it will be very interesting to see your implementation. The things that I saw with Fluxible look very verbose as for me..

**Comment by goatslacker** [comment]
Sure, I'll publish it to my fork omorrow/later today. I'll send a PR and then we can go from there.

**Comment by goatslacker** [comment]
A little later than promised since I'm sick with the flu but here it is #14

**Comment by voronianski** [comment]
@goatslacker @acdlite thanks for your isomorphic pull-requests! However I would like to keep this repo as simple as possible and make all solutions close to each other with the same client-side example.

I can create separate repo (smth like `isomorphic-flux-comparison`) where your solutions could be a nice fit. What do you think?

(PRs - https://github.com/voronianski/flux-comparison/pull/14, https://github.com/voronianski/flux-comparison/pull/15)

**Comment by acdlite** [comment]
@voronianski Yeah! I think it would be best to keep them separate. A project that involves routing would be ideal.

I'll update my PR. Thanks!
