### ISSUE TITLE
Suggestion: a series of Youtube videos walking new users through the code

### ISSUE THREAD

**Issue by msikma** [voronianski/flux-comparison#24]
I think this would make a very nice addition to the code itself. For new users it might be a bit difficult to understand exactly what is responsible for which part of the process and how data moves through the application. One way to illuminate this is by recording the screen and walking through the code, explaining things as you go along. It would take a bit of time to do, though—but I figured I'd make the suggestion anyway, in case you're interested in a challenge.

**Comment by voronianski** [comment]
@msikma I have a blog post with overview of the repo - http://pixelhunter.me/post/110248593059/flux-solutions-compared-by-example.

I have no experience with educational videos however I could try.. If I'll find out more interest in such video probably I'll think about it :)

**Comment by msikma** [comment]
Yeah, the blog post was very helpful, and I've seen it linked to quite a lot! :)

Going through all the different existing Flux implementations is undoable for someone who just wants to get a project on the rails. Your post also helped me pick Alt for my project not too long ago, so thanks! :+1:

**Comment by voronianski** [comment]
@msikma cool I'm also using Alt a lot right now, very good one :yellow_heart:
