### ISSUE TITLE
import error in flummox example error

### ISSUE THREAD

**Issue by suryagaddipati** [voronianski/flux-comparison#25]
shouldn't this be 
https://github.com/voronianski/flux-comparison/blob/master/flummox/js/Flux.js#L4

`import {AppActions} ....`

https://github.com/voronianski/flux-comparison/blob/master/flummox/js/actions/Actions.js#L6 

@acdlite

**Comment by acdlite** [comment]
@suryagaddipati It's correct, just a bit confusing I suppose. The import statement transpiles to `var Actions = require('./actions/Actions')`. The left hand side can be called whatever you like, whether it's Actions or AppActions or ActionsLalalalalalalala

Does that make sense? :)

**Comment by suryagaddipati** [comment]
@acdlite yeah that makes sense. I feel stupid. thanks for quick response.
