### ISSUE TITLE
Suggestion: Show error handling

### ISSUE THREAD

**Issue by jonjanisch** [voronianski/flux-comparison#29]
To make the examples complete and more realistic, I think error handling should be demonstrated. I'm struggling to come up with a good pattern for error handling myself.

**Comment by voronianski** [comment]
@jonjanisch this discussion may help you - http://pixelhunter.me/post/110248593059/flux-solutions-compared-by-example#comment-1845704464 basically there's no strict rules in error handling implementations, it's up to you to decide whether it's less verbose to have errors in stores or component's state.
