### ISSUE TITLE
Facebook Relay

### ISSUE THREAD

**Issue by barrystaes** [voronianski/flux-comparison#4]
As i understand, Relay technically isnt a full Flux implementation. (but are there any?)
It was first presented by Facebook at React.js Conf (January 2015).

This FAQ says its heavily inspired by Flux but simpler.
https://gist.github.com/wincent/598fa75e22bdfa44cf47

Perhaps its worth comparing here too?

**Comment by voronianski** [comment]
@barrystaes 

> Relay is a new framework from Facebook that provides data-fetching functionality for React applications. It was announced at React.js Conf (January 2015).

it's just announced, there's no code released yet.
