### ISSUE TITLE
Suggestion: nuclear.js

### ISSUE THREAD

**Issue by sompylasar** [voronianski/flux-comparison#41]
https://github.com/optimizely/nuclear-js
Quite robust implementation of Flux as a ready-to-use framework.

**Comment by jtremback** [comment]
I'm almost done with this, it's turning out a lot cleaner than a lot of the other fluxes in here.

**Comment by voronianski** [comment]
@jtremback :+1:

**Comment by jordangarcia** [comment]
:+1:

**Comment by jtremback** [comment]
Just started back up on this lol, had been a bit occupied the past couple weeks.

**Comment by jtremback** [comment]
@jordangarcia you should just submit yours, if it is done.

**Comment by voronianski** [comment]
added
