### ISSUE TITLE
sh: browserify: command not found

### ISSUE THREAD

**Issue by jtremback** [voronianski/flux-comparison#42]
When running `npm run build` in any of the flux implementation folders. The npm `scripts` field does not seem to add modules in the root folder's `node_modules` to it's path. I'm getting around this now by installing stuff globally, but that's ugly.

**Comment by jtremback** [comment]
Personally, I would give each folder a `package.json` with the full dependencies required for that implementation, possibly eliminating the root `package.json`.

OR

Run all build scripts from the root `package.json`.

**Comment by jtremback** [comment]
I'd also use watchify for a more pleasant build process. Would you accept a PR implementing any of these changes?

**Comment by voronianski** [comment]
@jtremback as you can see `watchify` is used on `npm start` - https://github.com/voronianski/flux-comparison/blob/master/facebook-flux/package.json#L4

I think we can do the same with `build` and browserify however switching to `package.json` for every implementation is preferable but will require more work.
