### ISSUE TITLE
Suggestion add Redux

### ISSUE THREAD

**Issue by mclouvem** [voronianski/flux-comparison#46]
It seems really good flux implementation [Redux](https://github.com/gaearon/redux)

**Comment by dizlexik** [comment]
:+1:

**Comment by dozoisch** [comment]
:+1:

**Comment by laurentvd** [comment]
:+1:

**Comment by voronianski** [comment]
will add it asap.

**Comment by laurentvd** [comment]
Awesome! It's pretty hard to pick a Flux implementation that suits me and Redux seems to gain traction lately.

**Comment by sjonner** [comment]
Seems like Flummox now recommends users to check out Redux in stead. From their [readme](https://github.com/acdlite/flummox#readme) (2015-07-08):

> Flummox 4.0 will likely be the last major release. Use Redux instead. It's really great.

**Comment by voronianski** [comment]
@sjonner yeah, redux is everywhere right now :fire:, I really plan to add example asap (this weekend hopefully)!

**Comment by taylorhakes** [comment]
Would be best to wait until redux 1.0 is released, so you don't have to change the example a few days after you create it.

**Comment by gaearon** [comment]
Redux 1.0 RC is out with breaking changes. **No further API changes are expected in 1.0 so it may be a good time to port the example to 1.0 RC (in a branch).** We will release 1.0 when the docs are ready.

You can find the comprehensive list of the changes in 1.0 RC against 1.0 alpha in the **[Redux 1.0 RC release notes](https://github.com/gaearon/redux/releases/tag/v1.0.0-rc)**. If you haven't ported to alpha yet, you'll need to **[apply changes from 0.12 to alpha first](https://github.com/gaearon/redux/pull/195#issue-92206321)**.

Thank you!
Please make sure to report any issues so we can release a stable 1.0.

**Comment by gaearon** [comment]
It's there actually: https://github.com/voronianski/flux-comparison/tree/master/redux.
This issue can be closed.
