### ISSUE TITLE
Indicate deprecated libraries

### ISSUE THREAD

**Issue by slava-sh** [voronianski/flux-comparison#54]
[Flummox](https://github.com/acdlite/flummox) and [Marty](http://martyjs.org/blog/2015/08/02/marty-last.html) are recommending that their users migrate to other solutions.

**Comment by voronianski** [comment]
@slava-sh that could be marked in some table I suppose, however I must admit that Flummox is pretty stable in use.

**Comment by slava-sh** [comment]
I suggest adding deprecation status info to the readme.
