### ISSUE TITLE
Suggestion: lux.js

### ISSUE THREAD

**Issue by tcurdt** [voronianski/flux-comparison#65]
see http://www.smashingmagazine.com/2015/06/qualities-of-good-flux-implementations/

**Comment by voronianski** [comment]
@tcurdt lux is already here - https://github.com/voronianski/flux-comparison/tree/master/lux

**Comment by tcurdt** [comment]
Doh! I guess I need to clean my glasses. Sorry about that.
Thanks for the good resource to pick the proper flux impl.
